### PR TITLE
plural file fixed

### PR DESCRIPTION
**Pull request by makrai**

### CODE REVIEW

**Comment by makrai** [comment]
I have to change this

**Comment by makrai** [comment]
https://github.com/kornai/4lang/blob/master/4lang.plural should be copied somewhere in this repo, but I don't know where.

**Comment by recski** [comment]
Why?

**Comment by makrai** [comment]
It is needed by definition_parser. It contains a list of plural nouns, which have to have a special machines like dogs => dog -0-> more

**Comment by recski** [comment]
But it is part of 4lang and an independent resource. The 4lang dictionary
itself is also "needed" by the definition parser in the sense that there is
probably no other resource written in this language...

**Comment by makrai** [comment]
OK, I can accept this.

**Pull request closed without merging**
